
services:
  bot:
    build:
      context: ./bot
    container_name: discord-bot
    env_file:
      - .env
    restart: always

  web:
    build:
      context: ./web
    container_name: discord-auth-web
    ports:
      - "5000:5000"
    volumes:
      - ./shared:/app/shared
    restart: always
